#!/bin/bash
brew install --verbose --build-bottle Formula/valet-php@"$PHPV".rb
brew bottle valet-php@$PHPV --json --force-core-tap
ls -all
#         Transfer to bintray
curl -T *.tar.gz -uhenkrehorst:$BINTRAY_KEY https://api.bintray.com/content/henkrehorst/homebrew-php/valet-php/valet-php/$FILENAME
curl -T *.json -uhenkrehorst:$BINTRAY_KEY https://api.bintray.com/content/henkrehorst/homebrew-php/valet-php/valet-php/newvalet-php@$PHPV.$OS.json